subscribers:

# Topics of Interest
# Webcams "/front_camera/image_raw"
# Rosbag Cam "/camera/image_rect_color"
# GEM Gazebo Cam "/camera_front/image_raw"


  camera_reading:
    topic: /camera/image_rect_color
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
